/**
 * Talent books and weapon ascension gems are only dropped by their source
 * domain on specific days — each domain offers 3 material families that
 * rotate Mon/Thu, Tue/Fri, Wed/Sat respectively, with every family available
 * on Sunday. The grouping below is keyed by the exact item key produced by
 * `nameToKey` in the gen-mats pipeline (matches `allCharacterMats_gen.json`
 * and `allWeaponMats_gen.json` item names byte-for-byte), so it stays
 * correct without re-deriving the family from the item's display name.
 */
export type FarmDayGroup = 'monThu' | 'tueFri' | 'wedSat'

export const FARM_DAY_GROUP_LABEL: Record<FarmDayGroup, string> = {
  monThu: 'Mon/Thu',
  tueFri: 'Tue/Fri',
  wedSat: 'Wed/Sat',
}

const MON_THU_ITEMS = [
  // Talent books
  'TeachingsOfFreedom',
  'GuideToFreedom',
  'PhilosophiesOfFreedom',
  'TeachingsOfProsperity',
  'GuideToProsperity',
  'PhilosophiesOfProsperity',
  'TeachingsOfTransience',
  'GuideToTransience',
  'PhilosophiesOfTransience',
  'TeachingsOfAdmonition',
  'GuideToAdmonition',
  'PhilosophiesOfAdmonition',
  'TeachingsOfEquity',
  'GuideToEquity',
  'PhilosophiesOfEquity',
  'TeachingsOfContention',
  'GuideToContention',
  'PhilosophiesOfContention',
  'TeachingsOfMoonlight',
  'GuideToMoonlight',
  'PhilosophiesOfMoonlight',
  // Weapon ascension gems
  'TileOfDecarabiansTower',
  'DebrisOfDecarabiansCity',
  'FragmentOfDecarabiansEpic',
  'ScatteredPieceOfDecarabiansDream',
  'LuminousSandsFromGuyun',
  'LustrousStoneFromGuyun',
  'RelicFromGuyun',
  'DivineBodyFromGuyun',
  'CoralBranchOfADistantSea',
  'JeweledBranchOfADistantSea',
  'JadeBranchOfADistantSea',
  'GoldenBranchOfADistantSea',
  'CopperTalismanOfTheForestDew',
  'IronTalismanOfTheForestDew',
  'SilverTalismanOfTheForestDew',
  'GoldenTalismanOfTheForestDew',
  'FragmentOfAnAncientChord',
  'ChapterOfAnAncientChord',
  'MovementOfAnAncientChord',
  'EchoOfAnAncientChord',
  'BlazingSacrificialHeartsTerror',
  'BlazingSacrificialHeartsHesitance',
  'BlazingSacrificialHeartsResolve',
  'BlazingSacrificialHeartsSplendor',
  'ArtfulDeviceFragment',
  'ArtfulDeviceReplica',
  'ArtfulDeviceInheritance',
  'ArtfulDeviceWish',
] as const

const TUE_FRI_ITEMS = [
  // Talent books
  'TeachingsOfResistance',
  'GuideToResistance',
  'PhilosophiesOfResistance',
  'TeachingsOfDiligence',
  'GuideToDiligence',
  'PhilosophiesOfDiligence',
  'TeachingsOfElegance',
  'GuideToElegance',
  'PhilosophiesOfElegance',
  'TeachingsOfIngenuity',
  'GuideToIngenuity',
  'PhilosophiesOfIngenuity',
  'TeachingsOfJustice',
  'GuideToJustice',
  'PhilosophiesOfJustice',
  'TeachingsOfKindling',
  'GuideToKindling',
  'PhilosophiesOfKindling',
  'TeachingsOfElysium',
  'GuideToElysium',
  'PhilosophiesOfElysium',
  // Weapon ascension gems
  'BorealWolfsMilkTooth',
  'BorealWolfsCrackedTooth',
  'BorealWolfsBrokenFang',
  'BorealWolfsNostalgia',
  'MistVeiledLeadElixir',
  'MistVeiledMercuryElixir',
  'MistVeiledGoldElixir',
  'MistVeiledPrimoElixir',
  'NarukamisWisdom',
  'NarukamisJoy',
  'NarukamisAffection',
  'NarukamisValor',
  'OasisGardensReminiscence',
  'OasisGardensKindness',
  'OasisGardensMourning',
  'OasisGardensTruth',
  'DrossOfPureSacredDewdrop',
  'SublimationOfPureSacredDewdrop',
  'SpringOfPureSacredDewdrop',
  'EssenceOfPureSacredDewdrop',
  'DeliriousDecadenceOfTheSacredLord',
  'DeliriousDesolationOfTheSacredLord',
  'DeliriousDemeanorOfTheSacredLord',
  'DeliriousDivinityOfTheSacredLord',
  'EmberOfLongNightFlint',
  'AfterglowOfLongNightFlint',
  'FlareOfLongNightFlint',
  'BlazeOfLongNightFlint',
] as const

const WED_SAT_ITEMS = [
  // Talent books
  'TeachingsOfBallad',
  'GuideToBallad',
  'PhilosophiesOfBallad',
  'TeachingsOfGold',
  'GuideToGold',
  'PhilosophiesOfGold',
  'TeachingsOfLight',
  'GuideToLight',
  'PhilosophiesOfLight',
  'TeachingsOfPraxis',
  'GuideToPraxis',
  'PhilosophiesOfPraxis',
  'TeachingsOfOrder',
  'GuideToOrder',
  'PhilosophiesOfOrder',
  'TeachingsOfConflict',
  'GuideToConflict',
  'PhilosophiesOfConflict',
  'TeachingsOfVagrancy',
  'GuideToVagrancy',
  'PhilosophiesOfVagrancy',
  // Weapon ascension gems
  'FettersOfTheDandelionGladiator',
  'ChainsOfTheDandelionGladiator',
  'ShacklesOfTheDandelionGladiator',
  'DreamOfTheDandelionGladiator',
  'GrainOfAerosiderite',
  'PieceOfAerosiderite',
  'BitOfAerosiderite',
  'ChunkOfAerosiderite',
  'MaskOfTheWickedLieutenant',
  'MaskOfTheTigersBite',
  'MaskOfTheOneHorned',
  'MaskOfTheKijin',
  'EchoOfScorchingMight',
  'RemnantGlowOfScorchingMight',
  'DreamOfScorchingMight',
  'OldenDaysOfScorchingMight',
  'BrokenGobletOfThePristineSea',
  'WineGobletOfThePristineSea',
  'SilverGobletOfThePristineSea',
  'GoldenGobletOfThePristineSea',
  'NightWindsMysticConsideration',
  'NightWindsMysticPremonition',
  'NightWindsMysticAugury',
  'NightWindsMysticRevelation',
  'SunderedGloryOfTheFarNorthScions',
  'UnyieldingDelusionOfTheFarNorthScions',
  'OblationOfTheFarNorthScions',
  'AureateRadianceOfTheFarNorthScions',
] as const

const ITEM_DAY_GROUP: Record<string, FarmDayGroup> = Object.fromEntries([
  ...MON_THU_ITEMS.map((item) => [item, 'monThu'] as const),
  ...TUE_FRI_ITEMS.map((item) => [item, 'tueFri'] as const),
  ...WED_SAT_ITEMS.map((item) => [item, 'wedSat'] as const),
])

/** Returns which day group (Mon/Thu, Tue/Fri, Wed/Sat) a domain-farmed item key drops on, or `undefined` for items not gated by a domain weekday rotation (e.g. mob drops, local specialties, Mora). */
export function getFarmDayGroup(itemKey: string): FarmDayGroup | undefined {
  return ITEM_DAY_GROUP[itemKey]
}
